Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Models/Corso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Iscrizione_Corsi.Models
{
    [Table("Corsi")]
    public class Corso
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdCorso { get; set; }

        [MaxLength(255)]
        public string TitoloCorso { get; set; }

        [MaxLength(255)]
        public string DescCorso { get; set; }

        public string CodiceCorso { get; set; }

        public DateTime DataCorso { get; set; }

        public ICollection<Iscrizione> Iscritti { get; set; }

        // IDEA GuID -
        //public Corso()
        //{
        //    CodiceCorso = Guid.NewGuid().ToString();
        //}
    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Models/Iscrizione.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Iscrizione_Corsi.Models
{
    [Table("Iscrizioni")]
    public class Iscrizione
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdIscrizione { get; set; }

        [ForeignKey("UtenteRef")]
        public Utente Utente { get; set; }

        [ForeignKey("CorsoRef")]
        public Corso Corso { get; set; }
    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Models/Utente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Iscrizione_Corsi.Models
{
    [Table("Utenti")]
    public class Utente
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Campo obbligatorio!")]
        public string Nome { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Campo obbligatorio!")]
        public string Cognome { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Campo obbligatorio!")]
        public string Indirizzo { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Campo obbligatorio!")]
        public DateTime DataNascita { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Serve un Username per accedere!")]
        public string Username { get; set; }

        [MaxLength(255)]
        [Required(ErrorMessage = "* Serve una Password per accedere!")]
        public string Password { get; set; }

        public ICollection<Iscrizione> Iscrizioni { get; set; }
    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Controllers/CorsoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Razor_Iscrizione_Corsi.Data;
using Razor_Iscrizione_Corsi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Iscrizione_Corsi.Controllers
{
    public class CorsoController : Controller
    {
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                  SETUP                   //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        private readonly InterfaceRepo<Corso> _repoCorso;

        public CorsoController(InterfaceRepo<Corso> corsoRepo)
        {
            _repoCorso = corsoRepo;
        }

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                 PAGINE                   //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        public IActionResult ElencoCorsi()
        {
            List<Corso> listaCorsi = (List<Corso>)_repoCorso.ReadAll();

            ViewBag.Title = "Elenco Corsi";

            return View(listaCorsi);
        }

        public IActionResult Dettagli()
        {
            return View();
        }

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                FUNZIONI                  //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//


    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Razor_Iscrizione_Corsi.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Razor_Iscrizione_Corsi.Data;

namespace Razor_Iscrizione_Corsi.Controllers
{
    public class HomeController : Controller
    {

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                 PAGINE                   //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        public IActionResult Index()
        {
            return View();
        }

    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Controllers/UtenteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Razor_Iscrizione_Corsi.Data;
using Razor_Iscrizione_Corsi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Iscrizione_Corsi.Controllers
{
    public class UtenteController : Controller
    {
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                  SETUP                   //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        private readonly InterfaceRepo<Utente> _repoUtente;

        public UtenteController(InterfaceRepo<Utente> utenteRepo)
        {
            _repoUtente = utenteRepo;
        }

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                 PAGINE                   //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        //public IActionResult ElencoUtenti()
        //{
        //    List<Utente> listaUtenti = (List<Utente>)_repoUtente.ReadAll();

        //    ViewBag.Title = "Elenco Utenti";

        //    return View(listaUtenti);
        //}

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        public IActionResult ElencoUtenti()
        {
            List<Utente> listaUtenti = (List<Utente>)_repoUtente.ReadAll();

            ViewBag.Title = "Elenco Utenti";

            return View(listaUtenti);
        }

        public IActionResult AreaPersonale()
        {
            if (HttpContext.Session.GetString("isLogged") == null)
            {
                return Redirect("/Utente/Login");
            }
            else
            {
                return View();
            }
        }

        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
        //                FUNZIONI                  //
        //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

        [HttpPost]
        public RedirectResult LoginCheck(Utente objUtente)
        {
            List<Utente> listaUtenti = (List<Utente>)_repoUtente.ReadAll();

            string username = objUtente.Username;
            string password = objUtente.Password;

            foreach (Utente item in listaUtenti)
            {
                if (item.Username.Equals(username) && item.Password.Equals(password))
                {
                    HttpContext.Session.SetString("isLogged", username);

                    return Redirect("/Home/Index");
                }
            }

            return Redirect("/Utente/Login");
        }

        [HttpPost]
        public IActionResult Inserisci(Utente objUtente)
        {
            if (ModelState.IsValid)
            {
                _repoUtente.Insert(objUtente);
                return Redirect("/Home/Index");
            }
            else
            {
                return View(objUtente);
            }
        }
    }
}

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Corso/Dettagli.cshtml
@{ Layout = "_Layout"; }

<h1 class="p-5 text-center text-light">Dettagli</h1>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Corso/ElencoCorsi.cshtml
@model List<Razor_Iscrizione_Corsi.Models.Corso>

    @{
    Layout = "_Layout";
    }

    <h1 class="p-5 text-center text-light">Lista Corsi</h1>

    <table class="table table-striped text-center" style="background-color: rgba(255,255,255,0.9);">
        <thead>
            <tr>
                <th>Codice</th>
                <th>Nome del corso</th>
                <th>Descrizione</th>
                <th>Inizio Corso</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.CodiceCorso</td>
                <td>@item.TitoloCorso</td>
                <td>@item.DescCorso</td>
                <td>@item.DataCorso</td>
            </tr>
            }

        </tbody>
    </table>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Home/Index.cshtml
@{ Layout = "_Layout"; }

<h1 class="p-5 text-center text-light">PALESTRA</h1>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>@ViewBag.Title</title>
</head>
<body style="background-image: url(https://images.pexels.com/photos/7031705/pexels-photo-7031705.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; ">

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(255,255,255,0.9)">
        <a class="navbar-brand" href="/">PALESTRA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/Corso/ElencoCorsi">Corsi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Utente/AreaPersonale">Area Personale</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Utente/ElencoUtenti">Elenco Utenti (TESTING)</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="d-flex">
        <div class="container" style="height: 100%; min-height: 100%; background-color: rgba(0,0,0,0.5) ">
            @RenderBody()
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Utente/AreaPersonale.cshtml
@{ Layout = "_Layout"; }

<h1 class="p-5 text-center text-light">Area Personale</h1>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Utente/ElencoUtenti.cshtml
@model List<Razor_Iscrizione_Corsi.Models.Utente>

    @{
    Layout = "_Layout";
    }

    <h1 class="p-5 text-center text-light">Lista Utenti</h1>

    <table class="table table-striped text-center" style="background-color: rgba(255,255,255,0.9);">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cognome</th>
                <th>Indirizzo</th>
                <th>Data di Nascita</th>
                <th>Username</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Cognome</td>
                <td>@item.Indirizzo</td>
                <td>@item.DataNascita</td>
                <td>@item.Username</td>
                <td>@item.Password</td>
            </tr>
            }

        </tbody>
    </table>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Utente/Login.cshtml
@model Razor_Iscrizione_Corsi.Models.Utente
@{ Layout = "_Layout"; }

<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <h1 class="p-5 text-center text-light">Login</h1>
    </div>
    <div class="col-md-4">

    </div>
</div>

<form asp-controller="Utente" asp-action="Login" method="post">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4 p-5" style="background-color: rgba(255,255,255,0.9)">

            <div class="form-group">
                <label>Username:</label>
                <input type="text" class="form-control" asp-for="Username" placeholder="Inserisci il tuo Username." />
            </div>
            <div class="form-group">
                <label>Password:</label>
                <input type="password" class="form-control" asp-for="Password" placeholder="Inserisci la tua Password." />
            </div>
            <hr />
            <button type="submit" class="btn btn-block btn-outline-dark">Login</button>
            <hr />
            <a href="/Utente/Register">Non sei ancora registrato? Clicca quì!</a>

        </div>
        <div class="col-md-4">

        </div>
    </div>
</form>

Razor_Iscrizione_Corsi/Razor_Iscrizione_Corsi/Views/Utente/Register.cshtml
@model Razor_Iscrizione_Corsi.Models.Utente
@{ Layout = "_Layout"; }

<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <h1 class="p-5 text-center text-light">Registrati</h1>
    </div>
    <div class="col-md-4">

    </div>
</div>

<form asp-controller="Utente" asp-action="Register" method="post">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4 p-5" style="background-color: rgba(255,255,255,0.9)">

            <div class="form-group">
                <label>Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" placeholder="Inserisci il Nome." />
                <span asp-validation-for="Nome"></span>
            </div>
            <div class="form-group">
                <label>Cognome:</label>
                <input type="text" class="form-control" asp-for="Cognome" placeholder="Inserisci il Cognome." />
                <span asp-validation-for="Cognome"></span>
            </div>
            <div class="form-group">
                <label>Indirizzo:</label>
                <input type="text" class="form-control" asp-for="Indirizzo" placeholder="Inserisci l''Indirizzo." />
                <span asp-validation-for="Indirizzo"></span>
            </div>
            <div class="form-group">
                <label>Data di Nascita:</label>
                <input type="date" class="form-control" asp-for="DataNascita" />
                <span asp-validation-for="DataNascita"></span>
            </div>
            <div class="form-group">
                <label>Username:</label>
                <input type="text" class="form-control" asp-for="Username" placeholder="Inserisci un Username." />
                <span asp-validation-for="Username"></span>
            </div>
            <div class="form-group">
                <label>Password:</label>
                <input type="password" class="form-control" asp-for="Password" placeholder="Inserisci una Password." />
                <span asp-validation-for="Password"></span>
            </div>
            <hr />
            <button type="submit" class="btn btn-block btn-outline-dark">Registrati!</button>

        </div>
        <div class="col-md-4">

        </div>
    </div>
</form>